# Tạo Tensor


In [6]:
!pip install torch
import torch
import numpy as np

# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print("Tensor từ list:\n", x_data, "\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("Tensor từ NumPy array:\n", x_np, "\n")

# Tạo tensor với các giá trị hằng số / ngẫu nhiên
x_ones = torch.ones_like(x_data)
print("Ones Tensor:\n", x_ones, "\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print("Random Tensor:\n", x_rand, "\n")

# In thuộc tính
print("Shape:", x_rand.shape)
print("Datatype:", x_rand.dtype)
print("Device:", x_rand.device)


  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/111.0 MB ? eta -:--:--
   ---------------------------------------- 0.5/111.0 MB 4.2 MB/s eta 0:00:27
    --------------------------------------- 2.4/111.0 MB 7.1 MB/s eta 0:00:16
   - -------------------------------------- 3.4/111.0 MB 6.5 MB/s eta 0:00:17
   - -------------------------------------- 5.2/111.0 MB 8.4 MB/s eta 0:00:13
   --- ------------------------------------ 8.4/111.0 MB 9.1 MB/s eta 0:00:12
   --- ------------------------------------ 8.4/111.0 MB 9.1 MB/s eta 0:00:12
   --- ------------------------------------ 9.4/111.0 MB 6.9 MB/s eta 0:00:15
   --- ------------------------------------ 10.0/111.0 MB 7.0 MB/s eta 0:00:15
   --- ------------------------------------ 10.7/111.0 MB 6.2 MB/s eta 0:00:17
   ---- ----------------------------------- 11.5/111.0 MB 5.9 MB/s eta 0:00:17
   ---- -------------

# Các phép toán

In [ ]:
# 1. Cộng x_data với chính nó
print("x_data + x_data:\n", x_data + x_data, "\n")

# 2. Nhân x_data với 5
print("x_data * 5:\n", x_data * 5, "\n")

# 3. Nhân ma trận x_data @ x_data.T
print("x_data @ x_data.T:\n", x_data @ x_data.T)


# Indexing & Slicing

In [7]:
# 1. Lấy hàng đầu tiên
print("Hàng đầu tiên:", x_data[0])

# 2. Lấy cột thứ 2
print("Cột thứ 2:", x_data[:, 1])

# 3. Giá trị ở hàng 2 cột 2
print("Giá trị (2,2):", x_data[1, 1])


Hàng đầu tiên: tensor([1, 2])
Cột thứ 2: tensor([2, 4])
Giá trị (2,2): tensor(4)


# Thay đổi shape

In [8]:
x = torch.rand(4, 4)
y = x.view(16, 1)  
print("Tensor reshape:\n", y)


Tensor reshape:
 tensor([[0.1739],
        [0.1487],
        [0.2971],
        [0.4060],
        [0.7977],
        [0.0507],
        [0.4317],
        [0.2932],
        [0.4777],
        [0.8531],
        [0.4073],
        [0.1185],
        [0.3702],
        [0.9267],
        [0.9863],
        [0.3908]])


# AUTOGRAD

In [9]:
x = torch.ones(1, requires_grad=True)
print("x:", x)

y = x + 2
print("y:", y)
print("grad_fn của y:", y.grad_fn)

z = y * y * 3
z.backward()

print("Đạo hàm z theo x:", x.grad)


x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x00000179885F69E0>
Đạo hàm z theo x: tensor([18.])


# MÔ HÌNH ĐẦU TIÊN VỚI torch.nn

## nn.Embedding

In [10]:
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

input_indices = torch.LongTensor([1, 5, 0, 8])
embeddings = embedding_layer(input_indices)

print("Input shape:", input_indices.shape)
print("Output shape:", embeddings.shape)
print("Embeddings:\n", embeddings)


Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[-0.3874, -0.4553,  0.8717],
        [ 0.1272, -0.7536,  2.1522],
        [ 0.7800, -0.0257,  1.5125],
        [ 1.6069,  1.1333,  0.5603]], grad_fn=<EmbeddingBackward0>)


## Xây dựng model bằng nn.Module

In [11]:
from torch import nn
import torch

class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output

model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]])
output_data = model(input_data)

print("Model output shape:", output_data.shape)
print("Output:\n", output_data)


Model output shape: torch.Size([1, 4, 2])
Output:
 tensor([[[-0.0221,  0.0413],
         [ 0.2513, -0.4641],
         [-0.1098, -0.2527],
         [-0.1248, -0.1326]]], grad_fn=<ViewBackward0>)
